import { expect, test, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { editor, openApp } from './app';

/**
 * The performance budgets, measured against the reference workspaces.
 *
 * The budgets are in the architecture proposal (NFR-2, NFR-3, NFR-4) and the
 * workspaces are committed under `fixtures/perf/`, generated by
 * `scripts/make-perf-fixtures.mjs`. Both matter: a budget measured against
 * whatever input was handy is a budget whose history means nothing.
 *
 * These assertions are written to be meaningful on hardware slower than a
 * developer's machine, because that is where they run. Where a number depends
 * on the machine, what is asserted is the part the application controls — see
 * the loop latency test, which subtracts the fixed debounce rather than
 * pretending a shared CI runner is a laptop.
 */

const FIXTURES = join(import.meta.dirname, '..', '..', 'fixtures', 'perf');
const workspace = (blocks: number) => readFileSync(join(FIXTURES, `${blocks}.tf`), 'utf8');

/** The debounce is deliberate delay, not slowness; it is not the app being slow. */
const DEBOUNCE_MS = 250;

type Latency = { p50: number; p95: number; max: number };

function percentiles(samples: number[]): Latency {
  const sorted = [...samples].sort((a, b) => a - b);
  return {
    p50: Math.round(sorted[Math.floor(sorted.length / 2)]!),
    p95: Math.round(sorted[Math.floor(sorted.length * 0.95)]!),
    max: Math.round(sorted[sorted.length - 1]!),
  };
}

/**
 * Puts a large workspace in the editor the way a person would: by pasting.
 *
 * Not by `fill()`. Playwright's fill on a contenteditable took 25 seconds for
 * this document and produced a 25-second long task, which looked exactly like
 * an application defect until a real paste of the same text turned out to take
 * 624 ms. Measuring the instrument is part of measuring the thing.
 */
async function paste(page: Page, source: string): Promise<void> {
  await page.evaluate(async (text) => {
    await navigator.clipboard.writeText(text);
  }, source);

  const area = editor(page);
  await area.click();
  await page.keyboard.press('ControlOrMeta+a');
  await page.keyboard.press('ControlOrMeta+v');
}

/** Waits until the diagram stops changing, which is when the analysis landed. */
async function diagramSettles(page: Page, atLeast: number): Promise<number> {
  await expect
    .poll(() => page.locator('.react-flow__node').count(), { timeout: 120_000, intervals: [200] })
    .toBeGreaterThanOrEqual(atLeast);
  return page.locator('.react-flow__node').count();
}

test.describe('analysis latency (NFR-4)', () => {
  // The analyzer is measured through the worker, which is how the application
  // actually calls it: message in, model out, WebAssembly in between. Timing
  // the Go function alone would flatter it by leaving out the boundary.
  for (const [blocks, budget] of [
    [50, 300],
    [200, 300],
    [1000, 1000],
  ] as const) {
    test(`${blocks} blocks stays under ${budget} ms at p95`, async ({ page }) => {
      test.setTimeout(180_000);
      await openApp(page);

      const measured = await page.evaluate(async (source) => {
        const url = performance
          .getEntriesByType('resource')
          .map((entry) => entry.name)
          .find((name) => /analyzer\.worker.*\.js$/.test(name));
        if (!url) throw new Error('the analyzer worker script was not found');

        const worker = new Worker(url);
        let id = 0;

        const analyze = (files: Record<string, string>) =>
          new Promise<number>((resolve) => {
            const mine = ++id;
            const started = performance.now();
            const onMessage = (event: MessageEvent) => {
              if ((event.data as { id: number }).id !== mine) return;
              worker.removeEventListener('message', onMessage);
              resolve(performance.now() - started);
            };
            worker.addEventListener('message', onMessage);
            worker.postMessage({ id: mine, files });
          });

        const files = { 'main.tf': source };

        // The first call pays for fetching and compiling the module. That cost
        // is real but it is a page-load cost, not a per-analysis one, so it is
        // reported separately rather than folded into the distribution.
        const cold = await analyze(files);
        for (let i = 0; i < 3; i++) await analyze(files);

        const samples: number[] = [];
        for (let i = 0; i < 20; i++) samples.push(await analyze(files));
        worker.terminate();

        return { cold, samples };
      }, workspace(blocks));

      const latency = percentiles(measured.samples);
      console.log(
        `analysis ${blocks} blocks: p50 ${latency.p50} ms, p95 ${latency.p95} ms, max ${latency.max} ms (cold ${Math.round(measured.cold)} ms)`,
      );

      expect(latency.p95).toBeLessThanOrEqual(budget);
    });
  }
});

test.describe('the loop (NFR-3)', () => {
  // One keystroke, not a typed line. The debounce restarts on every keystroke,
  // so timing a line of text would measure how fast the test types.
  test('a keystroke reaches the diagram within the budget', async ({ page, context }) => {
    test.setTimeout(180_000);
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await openApp(page);

    await paste(page, workspace(200));
    await diagramSettles(page, 200);

    const area = editor(page);
    const samples: number[] = [];

    for (let i = 0; i < 6; i++) {
      // A resource missing its first letter: invalid, so no node yet.
      await area.click();
      await page.keyboard.press('ControlOrMeta+End');
      await page.keyboard.type(`\nesource "aws_s3_bucket" "probe${i}" {}`);
      await page.waitForTimeout(900);

      const before = await page.locator('.react-flow__node').count();
      await page.keyboard.press('Home');

      const started = Date.now();
      await page.keyboard.type('r');
      await expect(page.locator('.react-flow__node')).toHaveCount(before + 1, { timeout: 30_000 });
      samples.push(Date.now() - started);
    }

    const latency = percentiles(samples);
    console.log(
      `keystroke to diagram at 200 blocks: p50 ${latency.p50} ms, p95 ${latency.p95} ms, max ${latency.max} ms`,
    );

    // What is asserted is the work, not the wait. 250 ms of the 500 ms budget
    // is a debounce we chose, and it costs the same on any hardware; leaving it
    // in would make this assertion mostly a measurement of a constant, and
    // would make a slower runner fail for a reason that is not a regression.
    expect(latency.p95 - DEBOUNCE_MS).toBeLessThanOrEqual(500 - DEBOUNCE_MS);
  });
});

test.describe('typing is never blocked (NFR-2)', () => {
  // The requirement's purpose: analysis runs in a worker so the editor stays
  // responsive however large the workspace is. Measured at the largest
  // reference workspace, which is where it would break if it were going to.
  test('the editor stays responsive on a thousand-resource workspace', async ({
    page,
    context,
  }) => {
    test.setTimeout(180_000);
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await openApp(page);

    await paste(page, workspace(1000));
    await diagramSettles(page, 1000);

    const samples = await page.evaluate(async () => {
      const content = document.querySelector('.cm-content') as HTMLElement;
      const measured: number[] = [];

      for (let i = 0; i < 20; i++) {
        const started = performance.now();
        content.dispatchEvent(
          new InputEvent('beforeinput', {
            inputType: 'insertText',
            data: 'x',
            bubbles: true,
            cancelable: true,
          }),
        );
        await new Promise((resolve) => requestAnimationFrame(() => resolve(null)));
        measured.push(performance.now() - started);
        await new Promise((resolve) => setTimeout(resolve, 60));
      }

      return measured;
    });

    const latency = percentiles(samples);
    console.log(
      `keystroke handling at 1000 blocks: p50 ${latency.p50} ms, p95 ${latency.p95} ms, max ${latency.max} ms`,
    );

    expect(latency.p95).toBeLessThanOrEqual(50);
  });
});

test.describe('the editor arrives before the analyzer (NFR-5)', () => {
  // The user-facing half of the payload budget. The analyzer is nearly two
  // megabytes; if the editor waited for it, every visit would begin with a
  // blank pane on a slow connection.
  //
  // The network is throttled through CDP rather than by intercepting the
  // request, because the module is fetched inside the worker and `page.route`
  // does not see a dedicated worker's requests. Throttling is also closer to
  // the situation being tested: a real slow connection, not a stalled route.
  test('the editor can be typed in while the analyzer is still downloading', async ({
    page,
    context,
  }) => {
    const client = await context.newCDPSession(page);
    await client.send('Network.emulateNetworkConditions', {
      offline: false,
      latency: 200,
      downloadThroughput: (400 * 1024) / 8,
      uploadThroughput: (400 * 1024) / 8,
    });

    await page.goto('/');

    const area = editor(page);
    await expect(area).toBeVisible({ timeout: 30_000 });

    // The diagram still says it has nothing to draw: the analyzer has not
    // answered yet. That is the state this test is about.
    await expect(page.getByTestId('diagram-waiting')).toBeVisible();

    await area.click();
    await page.keyboard.press('ControlOrMeta+End');
    await page.keyboard.type('\nresource "aws_vpc" "typed_early" {}');

    const typed = await page.evaluate(() =>
      (document.querySelector('.cm-content') as HTMLElement).innerText.includes('typed_early'),
    );
    expect(typed).toBe(true);

    // And it was still waiting while all of that happened.
    await expect(page.getByTestId('diagram-waiting')).toBeVisible();

    // Then the analyzer arrives on its own and draws what was typed while it
    // was away — nothing is lost by starting before it is ready.
    await client.send('Network.emulateNetworkConditions', {
      offline: false,
      latency: 0,
      downloadThroughput: -1,
      uploadThroughput: -1,
    });
    await expect(page.getByTestId('diagram')).toBeVisible({ timeout: 60_000 });
  });
});
