// Embeds the catalog into the Go module.
//
// The catalog lives at catalog/ because it is shared domain data, not Go code:
// the analyzer applies its rules and the interface reads its presentation.
// Go's embed directive cannot reach outside its own module, so the data is
// copied into a generated Go file instead of being duplicated by hand.
//
// CI regenerates and fails on any diff, the same mechanism that keeps the
// TypeScript types honest. Nothing here validates the catalog: that happens in
// Go, against the JSON Schema, where the rules are actually applied.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const catalogDir = path.join(repoRoot, 'catalog');
const output = path.join(repoRoot, 'core', 'internal', 'catalog', 'data.gen.go');

const files = fs
  .readdirSync(catalogDir)
  .filter((name) => name.endsWith('.json'))
  .sort();

if (files.length === 0) {
  console.error('No catalog files found in catalog/');
  process.exit(1);
}

const entries = files.map((name) => {
  const raw = fs.readFileSync(path.join(catalogDir, name), 'utf8');
  // Parse to fail early on malformed JSON, and to normalise formatting so a
  // whitespace change does not show up as a diff in generated Go.
  const parsed = JSON.parse(raw);
  return { name, json: JSON.stringify(parsed) };
});

const goSource = `// Code generated by scripts/build-catalog.mjs. DO NOT EDIT.
//
// Source: catalog/*.json
// Regenerate with: npm run generate

package catalog

// rawCatalogs holds each catalog file as it appears on disk, keyed by
// filename. Parsing and validation happen at load time in catalog.go.
var rawCatalogs = map[string]string{
${entries.map((e) => `\t${JSON.stringify(e.name)}: ${JSON.stringify(e.json)},`).join('\n')}
}
`;

const existing = fs.existsSync(output) ? fs.readFileSync(output, 'utf8') : null;
const relative = path.relative(repoRoot, output);

if (existing === goSource) {
  console.log(`up to date  ${relative}`);
} else if (process.argv.includes('--check')) {
  console.error(`OUT OF DATE ${relative}`);
  console.error('\nRun "npm run generate" and commit the result.\n');
  process.exit(1);
} else {
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, goSource, 'utf8');
  console.log(`written     ${relative}  (${files.join(', ')})`);
}
